server:
  port: 8080

spring:
  application:
    name: catalog-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  ai:
    mcp:
      server:
        protocol: SSE
        capabilities:
          tool: true
        name: catalog-service
        version: 0.1.0

management:
  endpoints:
    web:
      exposure:
        include: health,info
