apiVersion: agentgateway.solo.io/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: anthropic
  namespace: agentgateway-system
spec:
  type: anthropic
  provider:
    anthropic:
      url: https://api.anthropic.com
      authToken:
        secretRef:
          name: anthropic-api-key
          key: Authorization
