apiVersion: enterpriseagentgateway.solo.io/v1alpha1
kind: EnterpriseAgentgatewayPolicy
metadata:
  name: observability-policy
  namespace: agentgateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: agentgateway
  frontend:
    accessLog:
      attributes:
        add:
          - name: gen_ai.request.model
            expression: 'request.headers["x-model"]'
          - name: gen_ai.client
            expression: 'request.headers["x-client-id"]'
