apiVersion: agentgateway.solo.io/v1alpha1
kind: EnterpriseAgentgatewayPolicy
metadata:
  name: rate-limit-policy
  namespace: agentgateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: anthropic-route
  traffic:
    rateLimit:
      local:
        requests: 20
        unit: MINUTE
      tokenBudget:
        maxTokens: 50000
        unit: HOUR
