server:
  port: 8080

spring:
  application:
    name: notifications-service
  datasource:
    url: jdbc:h2:mem:notifications-service
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  ai:
    mcp:
      server:
        name: notifications-service
        version: 0.1.0

management:
  endpoints:
    web:
      exposure:
        include: health,info
