apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: catalog-service
  namespace: kagent
spec:
  url: http://catalog-service.cloud-cart-support.svc.cluster.local:8080/sse
  protocol: SSE
---
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: orders-service
  namespace: kagent
spec:
  url: http://orders-service.cloud-cart-support.svc.cluster.local:8080/sse
  protocol: SSE
---
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: customers-service
  namespace: kagent
spec:
  url: http://customers-service.cloud-cart-support.svc.cluster.local:8080/sse
  protocol: SSE
---
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: notifications-service
  namespace: kagent
spec:
  url: http://notifications-service.cloud-cart-support.svc.cluster.local:8080/sse
  protocol: SSE
